# Default values for croc-hunter.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

ServiceType: NodePort
ServicePort: 80
ContainerPort: 8080
Component: "croc-hunter"
Replicas: 3
Image: "quay.io/jkbuster/croc-hunter"
ImageTag: "latest"
ImagePullPolicy: "Always"
Cpu: "10m"
Memory: "128Mi"
# Ingress settings
Ingress:
  enabled: true
  domain: croc-hunter2.k8s.estrado.io
